{
  custJsDO.validatePlaceOrder="can't place order";
  try {
    custJsVO.placeOrder(product355DO,3);
    fail("Should have thrown exception");
  }
 catch (  final InvalidException ex) {
    assertThat(ex.getAdvisorClass(),classEqualTo(ActionValidationFacetViaMethod.class));
    assertThat(ex.getIdentifier().getMemberNaturalName(),equalTo("Place Order"));
    assertThat(ex.getMessage(),equalTo("can't place order"));
  }
}
